"""add_tasks_table.

Revision ID: 6e5c7cd6155d
Revises: 8d7d6a5e72d8
Create Date: 2026-06-07 17:35:36.828624

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6e5c7cd6155d"
down_revision: str | Sequence[str] | None = "8d7d6a5e72d8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("tasks",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("topic", sa.String(), nullable=False),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("input_data", sa.JSON(), nullable=False),
    sa.Column("result_data", sa.JSON(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("worker_id", sa.String(), nullable=True),
    sa.Column("retries", sa.Integer(), nullable=False),
    sa.Column("error_message", sa.String(), nullable=True),
    sa.PrimaryKeyConstraint("id")
    )
    op.alter_column("executions", "timestamp",
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("executions", "timestamp",
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_table("tasks")
    # ### end Alembic commands ###
